site:
  title: Boost.int128
  start_page: int128::overview.adoc
content:
  sources:
    - url: ..
      start_path: doc
output:
  dir: html
ui:
  bundle:
    url: https://github.com/boostorg/website-v2-docs/releases/download/ui-develop/ui-bundle.zip
  supplemental_files: ./supplemental-ui
  output_dir: int128/_
antora:
  extensions:
    - '@antora/lunr-extension'
